name: Continuous Integration

on:
  push:
    branches:
    - master
    - init
    tags:
    - '*'
  pull_request:

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v2

    - name: Set up Python 3.8 🐍
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install poetry 🦄
      uses: Gr1N/setup-poetry@v4

    - name: Load Poetry Cached Libraries ⬇
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry-

    - name: Install dependencies 🖥
      run: poetry install --no-interaction

    - name: Lint Code 🎎
      run: make lint

    - name: Check Types 📚
      run: make types

  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} 🐍
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry 🦄
      uses: Gr1N/setup-poetry@v4

    - name: Load Poetry Cached Libraries ⬇
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry-

    - name: Install dependencies 🖥
      run: |
        poetry install --no-interaction

    - name: Test Code 🔍
      run: make test

    - name: Send Coverage Report 📊
      if: matrix.python-version == 3.6 && matrix.os != 'windows-latest'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: poetry run coveralls

  docs:
    name: Test Docs
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v2

    - name: Set up Python 3.8 🐍
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install poetry 🦄
      uses: Gr1N/setup-poetry@v4
    
    - name: Install dependencies 🖥
      run: poetry install --no-interaction --extras "docs"

    - name: Build docs ⚒️
      run: make docs

  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest

    # deploy will only be run when there is a tag available
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [quality, test, docs]  # only run after all other stages succeeded

    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v2

    - name: Set up Python 3.8 🐍
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install poetry 🦄
      uses: Gr1N/setup-poetry@v4

    - name: Build ⚒️ Distributions
      run: |
        poetry build
        poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
